### ISSUE TITLE
Error on 2.1.50 RC2

### ISSUE THREAD

**Issue by AuroraWright** [ankipalace/advanced-browser#141]
When clicking "Browse" on the latest 2.1.50 build (RC2) on macOS, this error shows up:

```
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 2.1.50 (6718e678) Python 3.9.7 Qt 6.2.3 PyQt 6.2.3
Platform: Mac 12.3.1
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2022-04-01 13:29:20
Add-ons possibly involved: ⁨Advanced Browser⁩

Caught exception:
Traceback (most recent call last):
  File "aqt.browser.table.table", line 399, in _on_current_changed
  File "aqt.browser.browser", line 485, in on_current_row_changed
  File "aqt.browser.table.table", line 95, in get_current_card
  File "aqt.browser.table.model", line 221, in get_card
  File "aqt.browser.table.model", line 78, in get_row
  File "aqt.browser.table.model", line 86, in _fetch_row_and_update_cache
  File "aqt.browser.table.model", line 120, in _fetch_row_from_backend
  File "aqt.hooks_gen", line 708, in __call__
  File "/Users/aurora/Library/Application Support/Anki2/addons21/874215009/advancedbrowser/core.py", line 127, in _column_data
    c = self.table._state.get_card(item)
AttributeError: 'AdvancedBrowser' object has no attribute 'table'
```

The addon worked on a previous 2.1.50 beta for what it's worth (not sure which).

**Comment by ijgnd** [comment]
I also have this bug (with all other add-ons disabled) in linux. 

This should be caused by https://github.com/ankitects/anki/commit/dd16890c1120269e2c00b1357aad0268d9cf29f4.

**Comment by ijgnd** [comment]
Anki now seems to run hooks in the wrong order, see https://forums.ankiweb.net/t/anki-2-1-50-beta-6-release-candidate/18181/91?u=ijgnd

**Comment by dae** [comment]
@RumovZ any thoughts on the best approach here? The old addons snapshot doesn't show any other users of did_fetch_row, and the browser_will_show users don't appear to be dependent on an active search, so we could theoretically move the will_show hook a line up. Alternatively we could adjust our row fetching code to allow skipping the hook, but that might not work for this use case - the first row could end up getting formatted differently unless we avoided caching it and discarded it.

**Comment by RumovZ** [comment]
> so we could theoretically move the will_show hook a line up.

Sure. I only moved `self.setupSearch(card, search)` in https://github.com/ankitects/anki/pull/1679 above it because I thought `will_show()` should be as close to `.show()` as possible, but whatever makes most sense for add-ons.

**Comment by dae** [comment]
Ah, it's nice it was moved recently, that should reduce the chance of this causing any regressions 👍

**Comment by ijgnd** [comment]
thanks for the quick fix.
